credentials:
  usernames:
    hidden_name:
      email: hidden_email
      name: ユーザー
      password: hidden_pass
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - hidden_email